ProductionSystem.Web/Controllers/FasesController.cs
namespace ProductionSystem.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.EntityFrameworkCore;
    using ProductionSystem.Web.Data;
    using ProductionSystem.Web.Data.Entities;
    using ProductionSystem.Web.Data.Repositories.Interfaz;

    public class FasesController : Controller
    {
        private readonly IFaseRepository faseRepository;

        public FasesController(IFaseRepository faseRepository)
        {
            this.faseRepository = faseRepository;
        }

        // GET: Fases
        public IActionResult Index()
        {
            return View(this.faseRepository.GetAll());
        }

        // GET: Fases/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fase = await this.faseRepository.GetByIdAsync(id.Value);
            if (fase == null)
            {
                return NotFound();
            }

            return View(fase);
        }

        // GET: Fases/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Fases/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

        //Funcion para cambiar de fase, se llama cuando terminemos un proceso
        
        //Ir a produccion, ligado con el empleado, sacar d eacuerdo con la cuenta, buscar el empleado sacar el pedido y vamos a la tabla de pedidos para mostrarle el usuario
        //Deshechos aceptar los deshechos producto rterminado se cree solo, solo en despues de la fase 3.
        // Pedido tiene fase.
        

//Numero de la ultima fase nomas.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Fase fase)
        {
            if (ModelState.IsValid)
            {
               
                await this.faseRepository.CreateAsync(fase);

                var temp = this.faseRepository.GetLastRecord();

                fase.Numero = fase.Id;

                await this.faseRepository.UpdateAsync(fase);

                return RedirectToAction(nameof(Index));
            }
            return View(fase);
        }

        // GET: Fases/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fase = await this.faseRepository.GetByIdAsync(id.Value);
            if (fase == null)
            {
                return NotFound();
            }
            return View(fase);
        }

        // POST: Fases/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Fase fase)
        {
    
            if (ModelState.IsValid)
            {
                try
                {
                    await this.faseRepository.UpdateAsync(fase);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await this.faseRepository.ExistAsync(fase.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(fase);
        }

        // GET: Fases/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fase = await this.faseRepository.GetByIdAsync(id.Value);
            if (fase == null)
            {
                return NotFound();
            }

            return View(fase);
        }

        // POST: Fases/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var fase = await this.faseRepository.GetByIdAsync(id);
            await this.faseRepository.DeleteAsync(fase);
            return RedirectToAction(nameof(Index));
        }
    }
}

ProductionSystem.Web/Controllers/LineasController.cs
namespace ProductionSystem.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.EntityFrameworkCore;
    using ProductionSystem.Web.Data;
    using ProductionSystem.Web.Data.Entities;
    using ProductionSystem.Web.Data.Repositories.Interfaz;
    using ProductionSystem.Web.Models;

    //[Authorize]
    public class LineasController : Controller
    {
        private readonly ILineaRepository lineaRepository;

        public LineasController(ILineaRepository lineaRepository)
        {
            this.lineaRepository = lineaRepository;
        }


        public async Task<IActionResult> EditCategoria(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoria = await this.lineaRepository.GetCategoriaAsync(id.Value);
            if (categoria == null)
            {
                return NotFound();
            }

            return View(categoria);
        }

        [HttpPost]
        public async Task<IActionResult> EditCategoria(Categoria categoria)
        {
            if (this.ModelState.IsValid)
            {
                var lineaId = await this.lineaRepository.UpdateCategoriaAsync(categoria);
                if (lineaId != 0)
                {
                    //TODO: revisar por que esta cosa me da error
                    return this.RedirectToAction("Index");
                }
            }

            return this.View(categoria);
        }

        public async Task<IActionResult> AddCategoria(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var linea = await this.lineaRepository.GetByIdAsync(id.Value);
            if (linea == null)
            {
                return NotFound();
            }

            var model = new CategoriaViewModel { PoseedorId = linea.Id };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddCategoria(CategoriaViewModel model)
        {
            if (this.ModelState.IsValid)
            {
                await this.lineaRepository.AddCategoriaAsync(model);
                //TODO: revisar por que esta cosa me da error
                return this.RedirectToAction("Index");
            }

            return this.View(model);
        }


        public async Task<IActionResult> DeleteCategoria(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoria = await this.lineaRepository.GetCategoriaAsync(id.Value);
            if (categoria == null)
            {
                return NotFound();
            }

            return View(categoria);
        }

        
        [HttpPost, ActionName("DeleteCategoria")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmedCategoria(int id)
        {
            var categoria = await this.lineaRepository.GetCategoriaAsync(id);
            await this.lineaRepository.DeleteCategoriaAsync(categoria);
            return RedirectToAction(nameof(Index));
        }





        // GET: Lineas
        public IActionResult Index()
        {
            return View(this.lineaRepository.GetLineasConCategorias());
        }

        // GET: Lineas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var linea = await this.lineaRepository.GetLineaConCategoriaAsync(id.Value);
            if (linea == null)
            {
                return NotFound();
            }

            return View(linea);
        }

        // GET: Lineas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Lineas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Linea linea)
        {
            if (ModelState.IsValid)
            {
                await this.lineaRepository.CreateAsync(linea);
                return RedirectToAction(nameof(Index));
            }
            return View(linea);
        }

        // GET: Lineas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var linea = await this.lineaRepository.GetByIdAsync(id.Value);
            if (linea == null)
            {
                return NotFound();
            }
            return View(linea);
        }

        // POST: Lineas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Linea linea)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    await this.lineaRepository.UpdateAsync(linea);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await this.lineaRepository.ExistAsync(linea.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(linea);
        }

        // GET: Lineas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var linea = await this.lineaRepository.GetByIdAsync(id.Value);
            if (linea == null)
            {
                return NotFound();
            }

            return View(linea);
        }

        // POST: Lineas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var linea = await this.lineaRepository.GetByIdAsync(id);
            await this.lineaRepository.DeleteAsync(linea);
            return RedirectToAction(nameof(Index));
        }

        
    }
}

ProductionSystem.Web/Controllers/PagosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProductionSystem.Web.Data;
using ProductionSystem.Web.Data.Entities;
using ProductionSystem.Web.Data.Repositories.Interfaz;
using ProductionSystem.Web.Helpers;
using ProductionSystem.Web.Models;
using System.Linq;
using System.Threading.Tasks;

namespace ProductionSystem.Web.Controllers
{
    public class PagosController : Controller
    {
        private readonly DataContext _context;
        private readonly IConverterHelper _converterHelper;
        private readonly ICombosHelper _combosHelper;
        private readonly IValidatorHelper _validatorHelper;
        private readonly IPagoRepository _IpagoRepository;
        private readonly IProductoPagoRepository _productoPagoRepository;

        public PagosController(DataContext context,
            IConverterHelper converterHelper,
            ICombosHelper combosHelper,
            IValidatorHelper validatorHelper,
            IPagoRepository pagoRepository,
            IProductoPagoRepository productoPagoRepository)
        {
            _context = context;
            _converterHelper = converterHelper;
            _combosHelper = combosHelper;
            _validatorHelper = validatorHelper;
            _IpagoRepository = pagoRepository;
            _productoPagoRepository = productoPagoRepository;
        }

        // GET: Pagos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Pagos.Include(e => e.Empresa).ToListAsync());
        }

        // GET: Pagos/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

           
          

       
            return View(_productoPagoRepository.GetAllPagos(id));
        }

        // GET: Pagos/Create
        public IActionResult Create()
        {


            var model = new PagoViewModel
            {
                Empresas = _combosHelper.GetComboEmpresas(),
                ProductosFinales = _combosHelper.GetComboProductosReales(),
            };
            return View(model);
        }

        // POST: Pagos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PagoViewModel model)
        {
            
            
            
            
            if (ModelState.IsValid)
            {

                if(!_validatorHelper.IsEnoughProduct(model.IdProductoFinal,model.UnidadesPagadas))
                {
                    return RedirectToAction("Error");
                }

              
                var pago= await _converterHelper.ToPagoAsync(model);



                _context.Pagos.Add(pago);

                _context.SaveChanges();

                var producto = await _context.ProductoReal.FindAsync(model.IdProductoFinal);
                producto.stock = producto.stock - model.UnidadesPagadas;

                _context.ProductoReal.Update(producto);

                _context.SaveChanges();


                //Aqui tenemos que introducir producto pago con los datos del model.

                var productopago = await  _converterHelper.ToProductoPagoAsync(model);

                _context.ProductoPagos.Add(productopago);

                _context.SaveChanges();

                //Aqui tenemos que itroducir a inventarioEmpresa
                //Primero tenemos que verificar que no existael producto real combinado con la empresa
                
                if(!_validatorHelper.ProductStorageExists(model))
                {

                    var inventarioEmpresa =  await _converterHelper.ToInventarioEmpresaAsync(model);

                    _context.InventarioEmpresas.Add(inventarioEmpresa);

                    _context.SaveChanges();



                }
                else
                {

                    var inventarioEmpresa =  _context
                        .InventarioEmpresas
                        .FirstOrDefault(e => e.ProductoReal.Id == model.IdProductoFinal 
                        && e.Empresa.Id == model.EmpresaId);
                    inventarioEmpresa.Stock = inventarioEmpresa.Stock + model.UnidadesPagadas;

                    _context.InventarioEmpresas.Update(inventarioEmpresa);

                    _context.SaveChanges();

                }
                
                //Si existe extraemos y solamente lo actualizamos
                //Si no existe se procede a crear uno nuevo.

                return RedirectToAction("Index");


            }
            else
            {
                model.Empresas = _combosHelper.GetComboEmpresas();
               

            }

            return View(model);




        }

        public IActionResult Error()
        {


            return View();
        }



        private bool PagoExists(int id)
        {
            return _context.Pagos.Any(e => e.Id == id);
        }
    }
}

ProductionSystem.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>UB INDUSTRIES</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">UB INDUSTRIES</a>
            </div>
            <div class="navbar navbar-expand-lg navbar-light bg-light">
                <ul class="nav navbar-nav ">

                    @if (this.User.IsInRole("Administrador"))
                    {

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" role="combobox" aria-expanded="false" aria-haspopup="true" href="#" data-toggle="dropdown">Presentacion</a>
                            <div class="dropdown-menu bg-success" style="left: 0px; top: 0px; position: absolute; transform: translate3d(0px, 37px, 0px);" x-placement="bottom-start">
                                <a asp-area="" asp-controller="Etiquetas" asp-action="Index">Etiquetas</a>
                                <br />
                                <a asp-area="" asp-controller="Envases" asp-action="Index">Envases</a>
                                <br />
                                <a asp-area="" asp-controller="TipoProductos" asp-action="Index">Tipos de Productos</a>
                                <br />
                                <a asp-area="" asp-controller="Lineas" asp-action="Index">Lineas</a>
                                <br />
                                <a asp-area="" asp-controller="Presentaciones" asp-action="Index">Presentaciones</a>
                                <br />
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" role="combobox" aria-expanded="false" aria-haspopup="true" href="#" data-toggle="dropdown">Insumo</a>
                            <div class="dropdown-menu bg-success" style="left: 0px; top: 0px; position: absolute; transform: translate3d(0px, 37px, 0px);" x-placement="bottom-start">
                                <a class="dropdown-item" asp-area="" asp-controller="Insumos" asp-action="Index">Insumos</a>
                                <br />
                                <a class="dropdown-item" asp-area="" asp-controller="Recetas" asp-action="Index">Recetas</a>
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" role="combobox" aria-expanded="false" aria-haspopup="true" href="#" data-toggle="dropdown">Producto</a>
                            <div class="dropdown-menu bg-success" style="left: 0px; top: 0px; position: absolute; transform: translate3d(0px, 37px, 0px);" x-placement="bottom-start">
                                <a asp-area="" asp-controller="Productos" asp-action="Index">Productos</a>
                                <br />
                                <a asp-area="" asp-controller="ProductosReales" asp-action="Index">Productos Reales</a>
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" role="combobox" aria-expanded="false" aria-haspopup="true" href="#" data-toggle="dropdown">Pedido</a>
                            <div class="dropdown-menu bg-success" style="left: 0px; top: 0px; position: absolute; transform: translate3d(0px, 37px, 0px);" x-placement="bottom-start">
                                <a asp-area="" asp-controller="Pedidos" asp-action="Index">Pedidos</a>
                                <br />
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" role="combobox" aria-expanded="false" aria-haspopup="true" href="#" data-toggle="dropdown">Produccion</a>
                            <div class="dropdown-menu bg-success" style="left: 0px; top: 0px; position: absolute; transform: translate3d(0px, 37px, 0px);" x-placement="bottom-start">
                                <a asp-area="" asp-controller="Account" asp-action="Index">Gestionar Cuentas</a>
                                <br />
                                <a asp-area="" asp-controller="EmpleadosProduccion" asp-action="Index">Empleados</a>
                                <br />
                                <a asp-area="" asp-controller="Fases" asp-action="Index">Fases</a>
                                <br />
                                <a asp-area="" asp-controller="Producciones" asp-action="Index">Producciones</a>
                                <br />
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" role="combobox" aria-expanded="false" aria-haspopup="true" href="#" data-toggle="dropdown">Empresa</a>
                            <div class="dropdown-menu bg-success" style="left: 0px; top: 0px; position: absolute; transform: translate3d(0px, 37px, 0px);" x-placement="bottom-start">
                                <a asp-area="" asp-controller="Empresas" asp-action="Index">Empresas</a>
                                <br />
                                <a asp-area="" asp-controller="Pagos" asp-action="Index">Pagos</a>
                                <br />
                                <a asp-area="" asp-controller="InventarioEmpresas" asp-action="Index">Inventario de Empresas</a>
                            </div>
                        </li>

                    }


                    @if (this.User.IsInRole("Produccion"))
                    {
                        <li><a asp-area="" asp-controller="Pedidos" asp-action="PedidosPendientesUsuario">Pedidos Pendientes</a></li>
                        <li><a asp-area="" asp-controller="Producciones" asp-action="ProduccionUsuario">Produccion Actual</a></li>
                        <li><a asp-area="" asp-controller="Producciones" asp-action="ProduccionFinalizadaUsuarioAsync">Producciones Finalizadas</a></li>
                    }

                </ul>

                <ul class="nav navbar-nav navbar-right">
                    @if (this.User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="ChangeUser">@this.User.Identity.Name</a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Logout">Logout</a></li>
                    }
                    else
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="Login">Login</a></li>
                    }
                </ul>


            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - ProductionSystem.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>